---

gcpmachines:
  hosts:
    piranha1:
      ansible_host: 35.185.247.169
    piranha2: 
      ansible_host: 34.83.188.53
    piranha3:
      ansible_host: 34.82.100.193
  vars:
    ansible_user: shishirpatil

